### ISSUE TITLE
Question about Network Policies

### ISSUE THREAD

**Issue by dmlabs** [benc-uk/kubeview#6]
Hi Ben,

I like your idea and your project.
Do you have any plans to visualize also Kubernetes Network Policies from the networking.k8s.io/v1 API?
I mean this kind of Kubernetes ressources:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
```
I started something for Network Policies myself, but I am a System Engineer and not a Developer, that is why my project contains only bash scripts at the moment. :-)
https://github.com/dmlabs/kube-defcon

Kind Regards,
Domenic

**Comment by benc-uk** [comment]
NetworkPolicy is one area of Kubernetes I've not investigated yet, but I really should take a look!

From a very quick initial investigation it should be too hard to add, but the thing I'm struggling to see is the linkage between the policy object and the pods it is applied to, but that might be because I don't have a network policy plugin enabled in my cluster

What would you like to see, in the visual map view? Other than linkage between a policy object and pods?

**Comment by dmlabs** [comment]
`kubectl describe netpol <netpol>` gives an overview, how Kubernetes interprets the network policy.

In my project my idea is to get all network policies and pods as json and store them in a MongoDB. Then implement some logic that is able to connect the network policies machLabels with the Pod labels and create some kind of graphic.

I tough about view for each namespaces where arrows indicate which pods can communicate with each other or with other resources outside the cluster.
